Lab8/Lab8/Controllers/BrandController.cs
using Lab8.Models;
using Lab8.Services.Interfaces;
using Microsoft.AspNetCore.Mvc;

namespace Lab8.Controllers
{
    public class BrandController : Controller
    {
        private readonly IBrandService _brandService;
        public BrandController(IBrandService brandService)
        {
            _brandService = brandService;
        }
        // GET: /Brand
        public IActionResult Index()
        {
            var brands = _brandService.GetAllBrands();
            return View(brands);
        }
        // GET: /Brand/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: /Brand/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Brand brand)
        {
            if (!ModelState.IsValid)
                return View(brand);
            _brandService.CreateBrand(brand);
            return RedirectToAction(nameof(Index));
        }
        // GET: /Brand/Edit/5
        public IActionResult Edit(int id)
        {
            var brand = _brandService.GetBrandById(id);
            if (brand == null) return NotFound();
            return View(brand);
        }
        // POST: /Brand/Edit
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(Brand brand)
        {
            if (!ModelState.IsValid)
                return View(brand);
            _brandService.UpdateBrand(brand);
            return RedirectToAction(nameof(Index));
        }
        // GET: /Brand/Delete/5
        public IActionResult Delete(int id)
        {
            _brandService.DeleteBrand(id);
            return RedirectToAction(nameof(Index));
        }
    }
}

Lab8/Lab8/Controllers/CarController.cs
using Lab8.Models;
using Lab8.Services.Implementation;
using Lab8.Services.Interfaces;
using Microsoft.AspNetCore.Mvc;

namespace Lab8.Controllers
{
    public class CarController : Controller
    {
        private readonly ICarService _carService;
        private readonly ICarModelService _carModelService;
        public CarController(ICarService carService, ICarModelService carModelService)
        {
            _carService = carService;
            _carModelService = carModelService;
        }
        // GET: /Car
        public IActionResult Index()
        {
            return View(_carService.GetAllCars());
        }
        // GET: /Car/Details/5
        public IActionResult Details(int id)
        {
            var car = _carService.GetCarById(id);
            if (car == null) return NotFound();
            return View(car);
        }
        // GET: /Car/Create
        public IActionResult Create()
        {
            ViewBag.CarModels = _carModelService.GetCarModels();
            return View();
        }
        // POST: /Car/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Car car)
        {
            if (!ModelState.IsValid)
                return View(car);
            _carService.CreateCar(car);
            return RedirectToAction(nameof(Index));
        }
        // GET: /Car/Edit/5
        public IActionResult Edit(int id)
        {
            var car = _carService.GetCarById(id);
            if (car == null) return NotFound();
            ViewBag.CarModels = _carModelService.GetCarModels();
            return View(car);
        }
        // POST: /Car/Edit
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(Car car)
        {
            if (!ModelState.IsValid)
                return View(car);
            _carService.UpdateCar(car);
            return RedirectToAction(nameof(Index));
        }
        // GET: /Car/Delete/5
        public IActionResult Delete(int id)
        {
            _carService.DeleteCar(id);
            return RedirectToAction(nameof(Index));
        }
    }
}

Lab8/Lab8/Controllers/CarModelController.cs
using Lab8.Models;
using Lab8.Services.Interfaces;
using Microsoft.AspNetCore.Mvc;

namespace Lab8.Controllers
{
    public class CarModelController : Controller
    {
        private readonly ICarModelService _carModelService;
        private readonly IBrandService _brandService;
        public CarModelController(
        ICarModelService carModelService,
        IBrandService brandService)
        {
            _carModelService = carModelService;
            _brandService = brandService;
        }
        // GET: /CarModel
        public IActionResult Index()
        {
            var data = _carModelService.GetCarModels();
            return View(data);
        }
        // GET: /CarModel/Create
        public IActionResult Create()
        {
            ViewBag.Brands = _brandService.GetAllBrands();
            return View();
        }
        // POST: /CarModel/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(CarModel carModel)
        {
            if (!ModelState.IsValid)
            {
                ViewBag.Brands = _brandService.GetAllBrands();
                return View(carModel);
            }
            _carModelService.CreateCarModel(carModel);
            return RedirectToAction(nameof(Index));
        }
        // GET: /CarModel/Edit/5
        public IActionResult Edit(int id)
        {
            var carModel = _carModelService.GetCarModelById(id);
            if (carModel == null) return NotFound();
            ViewBag.Brands = _brandService.GetAllBrands();
            return View(carModel);
        }
        // POST: /CarModel/Edit
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(CarModel carModel)
        {
            if (!ModelState.IsValid)
            {
                ViewBag.Brands = _brandService.GetAllBrands();
                return View(carModel);
            }
            _carModelService.UpdateCarModel(carModel);
            return RedirectToAction(nameof(Index));
        }
        // GET: /CarModel/Delete/5
        public IActionResult Delete(int id)
        {
            _carModelService.DeleteCarModel(id);
            return RedirectToAction(nameof(Index));
        }
    }
}

Lab8/Lab8/Controllers/OrderController.cs
using Lab8.Models;
using Lab8.Services.Interfaces;
using Microsoft.AspNetCore.Mvc;

namespace Lab8.Controllers
{
    public class OrderController : Controller
    {
        private readonly IOrderService _orderService;
        private readonly ICustomerService _customerService;

        // Inject cả OrderService và CustomerService
        public OrderController(IOrderService orderService, ICustomerService customerService)
        {
            _orderService = orderService;
            _customerService = customerService;
        }

        // GET: /Order
        public IActionResult Index()
        {
            var orders = _orderService.GetAllOrders();
            return View(orders);
        }

        // GET: /Order/Create
        public IActionResult Create()
        {
            // Lấy danh sách khách hàng để hiển thị Dropdown chọn người mua
            ViewBag.Customers = _customerService.GetAllCustomers();
            return View();
        }

        // POST: /Order/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Order order)
        {
            // Kiểm tra tính hợp lệ
            if (!ModelState.IsValid)
            {
                // Nếu lỗi, load lại danh sách khách hàng
                ViewBag.Customers = _customerService.GetAllCustomers();
                return View(order);
            }

            _orderService.CreateOrder(order);
            return RedirectToAction(nameof(Index));
        }

        // GET: /Order/Delete/5
        public IActionResult Delete(int id)
        {
            _orderService.DeleteOrder(id);
            return RedirectToAction(nameof(Index));
        }
    }
}

Lab8/Lab8/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Lab 8 - Auto Parts Store</title>

    <link href="~/vendor/fontawesome-free/css/all.min.css" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">

    <link href="~/css/sb-admin-2.min.css" rel="stylesheet">

</head>

<body id="page-top">

    <div id="wrapper">

        <ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">

            <a class="sidebar-brand d-flex align-items-center justify-content-center" asp-controller="Home" asp-action="Index">
                <div class="sidebar-brand-icon rotate-n-15">
                    <i class="fas fa-car"></i>
                </div>
                <div class="sidebar-brand-text mx-3">Auto Parts <sup>Store</sup></div>
            </a>

            <hr class="sidebar-divider my-0">

            <li class="nav-item active">
                <a class="nav-link" asp-controller="Home" asp-action="Index">
                    <i class="fas fa-fw fa-tachometer-alt"></i>
                    <span>Trang chủ</span>
                </a>
            </li>

            <hr class="sidebar-divider">

            <div class="sidebar-heading">
                Quản lý kho
            </div>

            <li class="nav-item">
                <a class="nav-link" asp-controller="Brand" asp-action="Index">
                    <i class="fas fa-fw fa-flag"></i>
                    <span>Hãng xe (Brand)</span>
                </a>
            </li>

            <li class="nav-item">
                <a class="nav-link" asp-controller="CarModel" asp-action="Index">
                    <i class="fas fa-fw fa-list"></i>
                    <span>Dòng xe (Model)</span>
                </a>
            </li>

            <li class="nav-item">
                <a class="nav-link" asp-controller="Car" asp-action="Index">
                    <i class="fas fa-fw fa-car"></i>
                    <span>Xe (Car)</span>
                </a>
            </li>

            <hr class="sidebar-divider">

            <div class="sidebar-heading">
                Kinh doanh
            </div>

            <li class="nav-item">
                <a class="nav-link" asp-controller="Customer" asp-action="Index">
                    <i class="fas fa-fw fa-users"></i>
                    <span>Khách hàng</span>
                </a>
            </li>

            <li class="nav-item">
                <a class="nav-link" asp-controller="Order" asp-action="Index">
                    <i class="fas fa-fw fa-shopping-cart"></i>
                    <span>Đơn hàng</span>
                </a>
            </li>

            <hr class="sidebar-divider d-none d-md-block">

            <div class="text-center d-none d-md-inline">
                <button class="rounded-circle border-0" id="sidebarToggle"></button>
            </div>

        </ul>
        <div id="content-wrapper" class="d-flex flex-column">

            <div id="content">

                <nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">

                    <button id="sidebarToggleTop" class="btn btn-link d-md-none rounded-circle mr-3">
                        <i class="fa fa-bars"></i>
                    </button>

                    <ul class="navbar-nav ml-auto">
                        <div class="topbar-divider d-none d-sm-block"></div>

                        <li class="nav-item dropdown no-arrow">
                            <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button"
                               data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                <span class="mr-2 d-none d-lg-inline text-gray-600 small">Admin User</span>
                                <img class="img-profile rounded-circle" src="~/img/undraw_profile.svg">
                            </a>
                            <div class="dropdown-menu dropdown-menu-right shadow animated--grow-in"
                                 aria-labelledby="userDropdown">
                                <a class="dropdown-item" href="#">
                                    <i class="fas fa-user fa-sm fa-fw mr-2 text-gray-400"></i>
                                    Profile
                                </a>
                                <div class="dropdown-divider"></div>
                                <a class="dropdown-item" href="#" data-toggle="modal" data-target="#logoutModal">
                                    <i class="fas fa-sign-out-alt fa-sm fa-fw mr-2 text-gray-400"></i>
                                    Logout
                                </a>
                            </div>
                        </li>
                    </ul>
                </nav>
                <div class="container-fluid">
                    @RenderBody()
                </div>
            </div>
            <footer class="sticky-footer bg-white">
                <div class="container my-auto">
                    <div class="copyright text-center my-auto">
                        <span>Copyright &copy; Lab 8 Auto Parts Store 2024</span>
                    </div>
                </div>
            </footer>
        </div>
    </div>
    <a class="scroll-to-top rounded" href="#page-top">
        <i class="fas fa-angle-up"></i>
    </a>

    <div class="modal fade" id="logoutModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
         aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Ready to Leave?</h5>
                    <button class="close" type="button" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">×</span>
                    </button>
                </div>
                <div class="modal-body">Select "Logout" below if you are ready to end your current session.</div>
                <div class="modal-footer">
                    <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancel</button>
                    <a class="btn btn-primary" href="#">Logout</a>
                </div>
            </div>
        </div>
    </div>

    <script src="~/vendor/jquery/jquery.min.js"></script>
    <script src="~/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

    <script src="~/vendor/jquery-easing/jquery.easing.min.js"></script>

    <script src="~/js/sb-admin-2.min.js"></script>

    @await RenderSectionAsync("Scripts", required: false)

</body>

</html>